theme: jekyll-theme-slate
title: The good, the bad, and the controversial sailing the Amazon
description: Exploring the book reviews of [Amazon.com](https://www.amazon.com) between May 1996 - July 2014
